# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a457793f53ff91507cec55829e3aed42f7d4affeaf79ff7900839d57b2a06ed84f3943468d6379735435dd49025c98034fe42ce64adee0370d97e5ec3982ce55

test:
  secret_key_base: cd80dfee2e20359f72a4d5013760e3ec1f5d6e84f4ecadb34ff117037f1ca0b1cd31bc39543065cfd3973a3a289de6c89a50bd625c3feb466be5e9da435a5e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
